pipeline {
    agent any
	options{
		disableConcurrentBuilds()
	}
    stages {
        stage('Transfer') {
            steps{
				timeout(time: 60, unit: 'SECONDS') {
               		sh "ssh -p ${params.port} phillip@${params.ip} > ${params.out} < ./${params.pullSec}"
			   		sh "cat ${params.out}"
               		sh '''
			   		export HTTP_PROXY="http://172.30.70.51:8080"
			   		export HTTPS_PROXY="http://172.30.70.51:8080"
			   		export http_proxy="http://172.30.70.51:8080"
			   		export https_proxy="http://172.30.70.51:8080"
			    		'''
			   		sh "./setupEnv.sh"
			   		sh "python3 loadIP.py --dbhost ${params.dbhost} --dbport ${params.dbport} --dbuser ${params.dbuser} --dbpassword ${params.dbpassword} --machine ${params.machine}"
				}
            }
        }
    }
  post{
    	failure{
      		build job: 'HIPCHAT-ROOM-NOTIFICATION', parameters: [
					string(name: 'ROOM', value: '39'),
					string(name: 'COLOR', value: 'red'),
					string(name: 'AUTH_TOKEN', value: 'Zi70f1FTkdFPBLS9nc0DO1gvtnmSmcLcmXaYwbtv'),
					string(name: 'MESSAGE', value: "Job ${env.JOB_NAME} ERROR: ${env.BUILD_URL} failed to get trade front latencty ${params.url}")
					] 
      }
    }
}
