#!/bin/bash
IPList=(172.201.250.70 172.201.250.121 172.201.250.62 172.201.250.122)
function ListLatency {
	HOST=$1
	echo $HOST `date "+%Y-%m-%d %H:%M:%S"`
	ping -c 10 -i 0.2 $HOST |awk -F= '{print $4}' |awk '{print $1}' |grep -v "^$"
	echo "======================================================="
}

for i in ${IPList[*]}
do
	ListLatency ${i}
done
