pipeline {
    agent {
        docker {
            image 'python:3-alpine'
            args '-v /home/phillip/services/services-conf/wpad:/wpad'
        }
    }
    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
         disableConcurrentBuilds()
    }
    triggers {
        cron("@daily")
    }
    environment {
        HTTP_PROXY = 'http://172.30.50.121:8080'
        HTTPS_PROXY = 'http://172.30.50.121:8080'
    }
    stages {
        stage ('Generate PAC File') {
            steps {
                sh "proxy-pac-generation/gfwlist-to-pac.py --extra-hosts ${params.EXTRA_HOSTS}"
            }
        }
        stage ('Deploy') {
            steps {
                sh "mv proxy.pac /wpad/wpad.dat"
            }
        }
    }
}
